### ISSUE TITLE
Splits are not showing up in adjusted data from WIKI 

### ISSUE THREAD

**Issue by emptyopen** [quandl/quandl-python#100]
In fact, adjusted data is identical to non-adjusted data. Consider this example (stock = CGNX):
Here is output from 2017-11-20 to 2017-12-18. https://imgur.com/a/PAd4s

This is data pulled like so:
`test = quandl.get('WIKI/CGNX')`

Split ratio remains at 1.0 throughout, and adjusted & unadjusted values are identical. However there is ample evidence of a stock split around the end of October, and any properly adjusted data shows this: 
https://imgur.com/a/qGUfw (from Yahoo Finance, all values below $100).

**Comment by mbasset** [comment]
Hi @emptyopen,

This looks to be an issue with the data and not the python package. I would recommend you reach out to our support at connect@quandl.com. They will be able to help you with data related inquiries.
