### ISSUE TITLE
LICENSE file to be added

### ISSUE THREAD

**Issue by alen12345** [quandl/quandl-python#103]
Can you please add the license file in the root of the repo? This is suggested to include the package on conda-forge.

Thank you.

**Comment by mbasset** [comment]
Hi @alen12345,

Thanks for alerting us to this issue. We will get that into the repo and let you know when thats done.

**Comment by mbasset** [comment]
Hi @alen12345 ,

We have added a license file to the repo. Please let us know if you have any other concerns.

**Comment by sebix** [comment]
> Please let us know if you have any other concerns.

I have: Please also include the file in the sdist tarballs by including it in the `MANIFEST.in` file.

**Comment by mbasset** [comment]
@sebix we would gladly welcome a PR from you with the modified manifest and any other missing files required for the package to work on conda-forge.
