### ISSUE TITLE
European Commission Business and Consumer Surveys

### ISSUE THREAD

**Issue by ebbpy** [quandl/quandl-python#104]
I'm not sure if this issue has been raised before elsewhere. 

I was curious to learn why some of the free Quandl economic databases often update without the most recent data. For example, the European Commission Business and Consumer Surveys Quandl dataset doesn't currently include the most recent data (February, 2018). It looks like Quandl is updating on the correct release date, but the new data isn't available until subsequent updates.

I was also having similar issues with the Institute for Supply Management in January, however, this no longer seems to be an issue. 

Thanks in advance.

**Comment by sushant-hukeri** [comment]
Hi @ebbpy,

Thanks for reaching out to us! We take care of technical requests only through this forum. For this and other data-related issues, may I request you to email connect@quandl.com? Our data team will be sure to assist you.
