### ISSUE TITLE
store and read api key from local file

### ISSUE THREAD

**Issue by ulf1** [quandl/quandl-python#116]
### Current Way
```
import quandl
quandl.ApiConfig.api_key = "mysecretkey"
```

### Store a API Key
Save API Key string in a local text file, e.g. `$HOME/.quandl_apikey`
```
quandl.apikey_set("mysecretkey")
```

or a specified file, e.g.
```
quandl.apikey_set("mysecretkey", filepath="/data/.quandl_apikey")
```

Use cases

* Users who don't want to expose their API key when sharing a Jupyter Notebook
* Docker container with mount point `/data/` to external storage (It's really painful to inject it with run command, and storing keys and tokens inside container is bad practice)

### Implemention 
https://github.com/ulf1/updoon/blob/master/updoon/quandl_apikey.py

this would read the file with the api like 

```
import quandl
import updoon 
quandl.ApiConfig.api_key = updoon.quandl_apikey()
```

### Proposal 
Add `save_key` and `read_key` to `api_config.py`, e.g.

```
class ApiConfig:
     ....

def read_key(filepath=None):
    ...
    ApiConfig.api_key = ...
```

to do 
```
import quandl
quandl.read_key()
...
```

instead of exposing the API key within a script.

**Comment by mbasset** [comment]
Thanks @ulf1 ,

We have merged your changes into master. They will go out with our next release.
