### ISSUE TITLE
Quandl Intraday Time Series data 

### ISSUE THREAD

**Issue by icraj2** [quandl/quandl-python#119]
Hi, 

Does the Quandl API support Intraday Data? 5minutes, hourly data?

For example : 
```
 from alpha_vantage.timeseries import TimeSeries
 data, meta_data = ts.get_intraday(symbol=AAPL, interval='60min', outputsize='compact')
```

API document only has the details on how to retrieve EOD data with the date range. 
https://docs.quandl.com/docs/python-time-series#section-make-a-filtered-time-series-call

**Comment by mbasset** [comment]
Hi @icraj2, 

Thanks for reaching out. For questions such as these, please refer to our Help Center at https://help.quandl.com. Please also see our Docs & Help page at https://www.quandl.com/docs-and-help where you can get in touch with our Customer Success and Sales teams.
