### ISSUE TITLE
Zillow examples returning QECx02 | 404

### ISSUE THREAD

**Issue by andresn** [quandl/quandl-python#138]
**From your examples page:** [https://blog.quandl.com/api-for-housing-data](https://blog.quandl.com/api-for-housing-data)

**Attempted:** 
- http://www.quandl.com/api/v3/datasets/ZILL/S00022_A.csv
- http://www.quandl.com/api/v3/datasets/ZILL/Z90210_SPY.csv

**Result:**

QECx02 | 404 | You have submitted an incorrect Quandl code. Please check your Quandl codes and try again.

I'm not having any issues with other examples such as:
- https://www.quandl.com/api/v3/datasets/WIKI/AAPL.csv

**Comment by A-Scott-Rowe** [comment]
Hi @andresn,

Sorry for the delay. It seems that the blog post you linked is outdated and those datasets were deprecated. There is more recent documentation at https://www.quandl.com/data/ZILL-Zillow-Real-Estate-Research/usage/quickstart/python. Also if you take a look at https://www.quandl.com/data/ZILL you can search for datasets that still exist. 

I'm going to close this issue for now, but feel free to reopen if you have any other questions.
