### ISSUE TITLE
No module named 'quandl'

### ISSUE THREAD

**Issue by cbt36594** [quandl/quandl-python#140]
I'm python 3.7 and I already install quandl
but still can't import quandl
can fix this problem?

**Comment by TinusJ** [comment]
Got the same issue

**Comment by snehpatel3** [comment]
Hi there, 

Apologies for the late reply.

Could you please help us by sharing information about your current environment (answering the questions below)? We are trying to reproduce your issues internally, without success (please see images attached).

-Which version of Windows are you using? 
-Which version of Python, 3.7? Is it 32-bit or 64-bit?
-Can you provide a code snippet that you've tried?
-How did you install our quandl api? 

Please note, we currently don't have 3.7 outlined in our test suites or package metadata.  However, we will be updating our dependencies shortly and intend to include Python 3.7 and 3.8 support as well.

Regards, 
Quandl Team 

![import](https://user-images.githubusercontent.com/10570100/68160087-025a8080-ff21-11e9-8e48-5e116de6e27c.PNG)

![data](https://user-images.githubusercontent.com/10570100/68160098-071f3480-ff21-11e9-99bc-71ae30d68b94.PNG)

**Comment by couture-ql** [comment]
Closing due to lack of response.

'module not found' has come up before, but usually from those running Conda / Anaconda.  So far we have been unable to reproduce the issue on Windows.  We'd be happy to help if this continues to be a problem.

**Comment by Rajat456** [comment]
I am using Python 3.8.1(64 bit) on windows 10 and facing the same issue

 File "d:/Python/programs/DSAlgo/quandle_test.py", line 1, in <module>
    import quandl
ModuleNotFoundError: No module named 'quandl'

any suggestions??

**Comment by mrrinaligupta** [comment]
I'm facing the same issue while using Python 3.10 on windows. Does anyone know the reason?
