### ISSUE TITLE
Print statements?

### ISSUE THREAD

**Issue by max-sixty** [quandl/quandl-python#150]
Are the print statements (e.g. https://github.com/quandl/quandl-python/blob/v3.4.8/quandl/model/datatable.py#L81) in the library intentional? Could they be changed to logging?

**Comment by couture-ql** [comment]
Hi Max,

You're right.  That's quite silly.  We'll get that changed.

**Comment by max-sixty** [comment]
Thanks!

**Comment by couture-ql** [comment]
Resolved in #154
