### ISSUE TITLE
get eps diluted with python

### ISSUE THREAD

**Issue by machine85** [quandl/quandl-python#151]
Hello,

i saw your great product for getting Stock Prices 

is there is a way for get also keys ratios like eps diluted ?

regards,

Tomer

**Comment by Raquel003** [comment]
Hi Tomer, 

Thanks for your question. 

Our fundamentals databases cover ratios and fundamental indicators such as diluted EPS. We recommend exploring the Core US Fundamentals database which covers Earnings per Diluted Share (epsdil) as well as 100+ other indicators. Please see the links below. 

**Core US Fundamentals**
**Home page:** https://www.quandl.com/databases/SF1
**Documentation:** https://www.quandl.com/databases/SF1/documentation
**Ticker and Indicator Coverage:** https://www.quandl.com/databases/SF1/documentation?anchor=coverage 
**API and Python usage examples** - see example 7 which explains how to retrieve data for specific indicators: https://www.quandl.com/databases/SF1/documentation?anchor=getting-started
**Sample Data:** https://www.quandl.com/databases/SF1/documentation?anchor=sample-data

I hope this helps. Please email us at connect@quandl.com if you have any other questions.

**Comment by A-Scott-Rowe** [comment]
Closing, but feel free to reopen if you have any other questions.
