### ISSUE TITLE
bulkdownload error on CHRIS database

### ISSUE THREAD

**Issue by gborrageiro** [quandl/quandl-python#152]
hello,

I am getting an error now when attempting to do a bulkdownload on the CHRIS database.
This worked previously.

```
import quandl

fname = '/tmp/CHRIS_data.zip'
quandl.ApiConfig.api_key = api_key  # hidden obviously
quandl.bulkdownload('CHRIS', filename=fname, download_type='complete')

Traceback (most recent call last):
  File "/opt/miniconda/envs/sipp/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-7e124b74a5f3>", line 6, in <module>
    quandl.bulkdownload('CHRIS', filename=fname, download_type='complete')
  File "/opt/miniconda/envs/sipp/lib/python3.8/site-packages/quandl/bulkdownload.py", line 24, in bulkdownload
    return Database(database).bulk_download_to_file(filename, params=kwargs)
  File "/opt/miniconda/envs/sipp/lib/python3.8/site-packages/quandl/model/database.py", line 46, in bulk_download_to_file
    r = Connection.request('get', path_url, **options)
  File "/opt/miniconda/envs/sipp/lib/python3.8/site-packages/quandl/connection.py", line 38, in request
    return cls.execute_request(http_verb, abs_url, **options)
  File "/opt/miniconda/envs/sipp/lib/python3.8/site-packages/quandl/connection.py", line 50, in execute_request
    cls.handle_api_error(response)
  File "/opt/miniconda/envs/sipp/lib/python3.8/site-packages/quandl/connection.py", line 114, in handle_api_error
    raise klass(message, resp.status_code, resp.text, resp.headers, code)
quandl.errors.quandl_error.NotFoundError: (Status 404) (Quandl Error QECx02) You have submitted an incorrect Quandl code. Please check your Quandl codes and try again.
```

any ideas?
regards
Gabriel

**Comment by gborrageiro** [comment]
```
$ pip list | grep Quandl
Quandl           3.5.0
```

**Comment by Raquel003** [comment]
Hi Gabriel, 

Thank you for your question. 

Free data on Quandl, such as the CHRIS database, may not be bulk downloaded. 

If you are looking for a Continuous Futures database that may be bulk downloaded, we do have a premium Continuous Futures database here: https://www.quandl.com/databases/SCF. To learn more about what this database covers, please see: https://www.quandl.com/databases/SCF/documentation. This database is in tables format and uses the tables API. See API usage examples here: https://www.quandl.com/databases/SCF/usage/quickstart/api. See Python usage examples here: https://www.quandl.com/databases/SCF/usage/quickstart/python. If you subscribe to the data, you will be able to bulk download it using Python. The command would be: 

quandl.export_table('SCF/PRICES')

I hope this information helps. If you have any other questions, please email us at connect@quandl.com.

**Comment by gborrageiro** [comment]
Hello,

This must be a recent change?
I used to be able to do the bulk download.

Thank you,
Gabriel

**Comment by Raquel003** [comment]
Hi Gabriel, 

Thanks very much - I will ask our team to check our past records of ever enabling bulk download for the CHRIS database. 

In any case, we can confirm that it is not currently possible since it is a free database and we do not plan on enabling bulk download for free databases. 

You can of course still download data from the CHRIS database, but it will have to be by individual time-series rather than a bulk download of all the time-series in the CHRIS database. See Python examples here: https://www.quandl.com/data/CHRIS-Wiki-Continuous-Futures/usage/quickstart/python. 

Kind regards, 
Raquel

**Comment by A-Scott-Rowe** [comment]
Closing, but feel free to reopen if you have any other questions.
