### ISSUE TITLE
Test table?

### ISSUE THREAD

**Issue by max-sixty** [quandl/quandl-python#156]
We have code which uses `export_table`, and we have some tests which ensure the code works. Would it be possible to provision a small datatable that people could use in these tests? 

We're currently using the smallest table we have a subscription for, and it looks like this repo internally use Zacks for its tests. That involves pulling a decent amount of data from Quandl, which is inefficient for Quandl and causes our tests to run slowly.

Thanks!

**Comment by A-Scott-Rowe** [comment]
Hi @max-sixty,

You could possibly use SHARADAR/INDICATORS. However this will count towards your daily rate limits. It is generally advised to mock the responses you are getting from us in your tests. We use a package called [httpretty](https://pypi.org/project/httpretty/) to mock out our calls to the api. You can see an example [here](https://github.com/quandl/quandl-python/blob/master/test/test_datatable.py#L155) of how we are using it to mock the response from the export feature.

**Comment by max-sixty** [comment]
Perfect, this is great, thanks!
