### ISSUE TITLE
403 Errors when calling quandl.get

### ISSUE THREAD

**Issue by andystanley** [quandl/quandl-python#160]
Getting 403 errors when calling `quandl.get`. Here's a couple examples:
```
(Pdb) quandl.get('EIA/PET_RWTC_D')
*** quandl.errors.quandl_error.QuandlError: (Status 403) Something went wrong. Please try again. If you continue to have problems, please contact us at connect@quandl.com.
(Pdb) quandl.get_table('ZACKS/FC', ticker='AAPL')
*** quandl.errors.quandl_error.QuandlError: (Status 403) Something went wrong. Please try again. If you continue to have problems, please contact us at connect@quandl.com.
```

I started experiencing this on Friday. Originally thought it was a temporary issue, but still not working on Monday.

**Comment by couture-ql** [comment]
Hi Andy,

If you could email connect@quandl.com we'll be happy to troubleshoot any issues your having.  Support may require some extra information from you, such as  your API Key, and we do not want you to publish that here.

Regards

**Comment by andystanley** [comment]
Thanks I'll do that!
