### ISSUE TITLE
Quandl's get function doesn't support multiset calls to SEC data

### ISSUE THREAD

**Issue by BlackArbsCEO** [quandl/quandl-python#24]
Hi. Love the API, but found a possible bug.

From the docs the get function is supposed to support a call such as:
`mydata = Quandl.get(["NSE/OIL.4","WIKI/AAPL.1"])`

However when I run the following code it returns an empty data frame:
`start = '2013-12-01', auth_token = 'my_auth_token'`
>>> a_b = q.get(['RAYMOND/FB_REVENUE_A','RAYMOND/FB_NET_INCOME_A'], authtoken=auth_token, trim_start = start)
>>> print( a_b )
Empty DataFrame
Columns: []
Index: []

I confirmed that the Quandl database had the data items in question by running the following code:
>>> a = q.get('RAYMOND/FB_NET_INCOME_A', authtoken=auth_token, trim_start = start)
>>> b = q.get('RAYMOND/FB_REVENUE_A', authtoken=auth_token, trim_start = start)
>>> print( a, b )
                 Value
Date                  
2013-12-31  1500000000                
Date                  
2013-12-31  7872000000

**Comment by jbyck** [comment]
Hi BlackArbsCEO. We're very sorry for the extremely long delay in responding to your issue. We are actively working on an updated version of the Quandl Python package, which will support these type of requests.
