### ISSUE TITLE
cache - reduce number of API calls - provide offline access of ever called data

### ISSUE THREAD

**Issue by femtotrader** [quandl/quandl-python#30]
Hello,

It will be nice to provide a cache mechanism to Quandl Python.
[`requests`](http://requests.readthedocs.org/) and [`requests-cache`](http://requests-cache.readthedocs.org/) could help.
You can see my code here
https://github.com/femtotrader/pandas_datareaders/

Kind regards

**Comment by jbyck** [comment]
Thanks femotrader, but we do not have any plans to introduce a caching layer into the package. We view this package as thin layer around our API, and we are hesitant to add additional complexity, which may be confusing to some users.

**Comment by femtotrader** [comment]
Is it still something you don't want ?

see http://pandas-datareader.readthedocs.io/en/latest/cache.html

I had a look at https://github.com/quandl/quandl-python/blob/e2540dc8333c03802583344820bb0dd6b93f07df/quandl/connection.py#L38

I think you just need an extra parameter (`session` for example)
`session` will be set to `None` by default

You will have

https://github.com/quandl/quandl-python/blob/e2540dc8333c03802583344820bb0dd6b93f07df/quandl/connection.py#L41

```python
    @classmethod
    def execute_request(cls, http_verb, url, **options):
        try:
            func = getattr(requests, http_verb)
            response = func(url, **options)
```

I don't think that's a very invasive modification but can be very useful!

**Comment by femtotrader** [comment]
```python
    @classmethod
    def execute_request(cls, http_verb, url, **options, session=None):
        try:
            if session is None:
                session = requests.Session()
            func = getattr(requests, http_verb)
            response = func(url, **options)
```

**Comment by femtotrader** [comment]
in fact... to be even less invasive session should comme from `options` kwargs.

**Comment by femtotrader** [comment]
```python
@classmethod
    def execute_request(cls, http_verb, url, **options):
        try:
            if 'session' not in options:
                session = requests.Session()
            func = getattr(requests, http_verb)
            response = func(url, **options)
```

**Comment by femtotrader** [comment]
Thanks @ericremoreynolds but passing `session` would be a much cleaner approach than monkey patch !
