### ISSUE TITLE
ENH,BLD: conda recipe

### ISSUE THREAD

**Issue by westurner** [quandl/quandl-python#68]
A conda recipe for quandl-python could be helpful.

Docs

* http://conda.pydata.org/docs/building/build.html
* http://conda.pydata.org/docs/using/envs.html#share-an-environment
* http://www.pydanny.com/building-conda-packages-for-multiple-operating-systems.html #
  * ``conda skeleton pypi quandl-python``

Examples

* https://github.com/conda/conda-recipes
* https://github.com/cloudera/ibis/tree/master/conda-recipes
* https://conda-forge.github.io/
  * http://anaconda.org/conda-forge

**Comment by mbasset** [comment]
Hi @westurner 

That sounds interesting. We would welcome a PR with the need changes for conda support.

**Comment by machbio** [comment]
@mbasset there is currently a broken version of Quandl on default Anaconda channel as of now..

**Comment by mbasset** [comment]
@machbio Could you elaborate on how the package is broken? Our newest package has not yet been uploaded to Anaconda so some of the new features will not work.

**Comment by machbio** [comment]
quandl: 2.8.9 is the version on Conda - it does not have ApiConfig ; i am not sure whether you supported API calls in that version.

**Comment by mbasset** [comment]
@machbio You will need to look at our older docs for the version until the new 3.x release is updated on conda. https://github.com/quandl/quandl-python/tree/v2.8.7 

However we highly recommend you use the new version as it includes many improvements and fixes. Not sure what system / python version you're running on however you should be able to install the new version using pip for now as described in our instructions.

**Comment by machbio** [comment]
Yes, the Pip install works Good.. just wanted to let you know about the broken Conda install..

**Comment by westurner** [comment]
``conda install pip; pip install quandl`` should work.

**Comment by westurner** [comment]
It's also possible to build from git.

http://conda.pydata.org/docs/building/meta-yaml.html#source-from-git

```yaml
source:
  git_url: https://github.com/quandl/quandl-python.git
  git_rev: v3.0.0
```

**Comment by westurner** [comment]
Thanks!
