### ISSUE TITLE
pyasn1 distro installation fails for Quandl 3.0.1

### ISSUE THREAD

**Issue by PruthviKumarBK** [quandl/quandl-python#72]
Hi All,

I get the following error on installing Quandl 3.0.1 for Python 2.7.

Processing dependencies for Quandl==3.0.1
Searching for pyasn1
Reading https://pypi.python.org/simple/pyasn1/
Download error on https://pypi.python.org/simple/pyasn1/: [Errno 11004] getaddri
nfo failed -- Some packages may not be found!
Couldn't find index page for 'pyasn1' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [Errno 11004] getaddrinfo fai
led -- Some packages may not be found!
No local packages or download links found for pyasn1
error: Could not find suitable distribution for Requirement.parse('pyasn1')

Please suggest if there is an alternative. 

Thanks,
Best,
Pruthvi

**Comment by mbasset** [comment]
Hi @PruthviKumarBK this is very strange. Could you give us more information about your machine. We have verified the package dependency in your log appears to exist in the pypi library here so we are not sure why you are unable to download that package: 

https://pypi.python.org/simple/pyasn1/

Also would you be able to provide us with the commands you used to install our package?

**Comment by PruthviKumarBK** [comment]
Hi @mbasset. Thanks for your reply. 


If the package dependency is satisfied, its strange why i get broken while attempting to install Quandl package. This has happened to me in more than one machine. One of the machines sits behind a proxy so i presumed it might be some firewall issues causing the break. Again, i did it another machine free from proxy's but receive different problems. This time around vc++ compiler. Its strange because i can install every other package but this one breaks. 

I have attached the logs FYR.

![image](https://cloud.githubusercontent.com/assets/11025372/15735110/9100424a-28b3-11e6-9b3c-cf766b841ecb.png)

![image](https://cloud.githubusercontent.com/assets/11025372/15735119/9fa2be9a-28b3-11e6-9f81-7445df398844.png)

**Comment by PruthviKumarBK** [comment]
I am using pip to install the package. pip install quandl. While the package's dependencies failed, i tried manually installing each one of them. Even after, when i try to request the API's contents using Python's Request, i get this error: 
Error. Error code:  <urlopen error [Errno 11004] getaddrinfo failed>

I presume this is probably due to firewall.

**Comment by PruthviKumarBK** [comment]
I have tried to install it on a proxy free linux distro and this is the error i receive. 

![image](https://cloud.githubusercontent.com/assets/11025372/15735317/571a2602-28b5-11e6-8da5-600865985271.png)

**Comment by mbasset** [comment]
Hi @PruthviKumarBK. Looks like in both cases your having issues due to library dependencies. Though I suspect it is different for the two different OS'.

For Windows it looks your missing the expected compilers and so it cannot install the numpy library via the python pypi package. You may want to try following some of the suggestions here for this specific package: http://stackoverflow.com/questions/11200137/installing-numpy-on-64bit-windows-7-with-python-2-7-3

For Linux it looks like you need the libffi package dependency. On Ubuntu this would be https://launchpad.net/ubuntu/+source/libffi and you should be able to install it with aptitude installer `apt-get install libffi`

**Comment by PruthviKumarBK** [comment]
Hi @mbasset ,

Thanks for your reply. Whats interesting is, i have numpy installed on the windows machine and libffi is also available to yum in linux. Despite this the same errors persist. I know its something to do with the firewall restrictions/similar but i am unable to get exact handle to fix. Despite having a dedicated package in python, due to this issue i am resolving to usage to API's at this point. I will update you once i find a fix. 

Thanks,
Pruthvi

**Comment by mbasset** [comment]
@PruthviKumarBK Thanks for the update. Given that you already have numpy and libffi in windows my guess would be that the python package system cannot find the binary you installed an so is attempting to retrieve and compile it from pypi.

For the linux one that is very strange. Please do let us know once you have found a solution.
