### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by klounix** [quandl/quandl-python#73]
I'm trying to install quandl for python3 but the same error appear in the end:

too much text so I putted in pastebin: http://pastebin.com/VG0hsuBN

**Comment by michaelfich** [comment]
Ideally, when using `pip install`, this would be done without using `sudo` and instead be installed as the user which installed python.  If unable to do so, you may want to try running the sudo command with `-H` which appears to be recommended by the error log.

You may also need to install `libssl-dev` using the following command as well:
```
apt-get install libssl-dev
```

**Comment by klounix** [comment]
I installed the lib and used root to install and now it finally works! thank you so much \o/
