### ISSUE TITLE
Return 3D datastructure when a list of several symbols is given

### ISSUE THREAD

**Issue by femtotrader** [quandl/quandl-python#74]
Hello,

```python
import Quandl
Quandl.get(["CHRIS/CME_ES1", "CHRIS/CME_NQ1"])
```

returns a DataFrame

Isn't there a way to get a [Pandas Panel](http://pandas.pydata.org/pandas-docs/stable/dsintro.html#panel) or an [xarray.DataArray](https://github.com/pydata/xarray)

An other approach could be to simply return an ordered dict with DataFrame as "value" and ticker as key.

User will be responsible for converting to 3D datastructure.

Kind regards

**Comment by femtotrader** [comment]
An example with Pandas DataReader

```python
In [1]: import pandas_datareader as pdr
In [12]: pdr.DataReader(["GOOG", "IBM"], "yahoo")
Out[2]:
<class 'pandas.core.panel.Panel'>
Dimensions: 6 (items) x 1630 (major_axis) x 2 (minor_axis)
Items axis: Open to Adj Close
Major_axis axis: 2010-01-04 00:00:00 to 2016-06-23 00:00:00
Minor_axis axis: GOOG to IBM
```

**Comment by femtotrader** [comment]
Here is a quick idea :


```python

import six
import collections
import Quandl

def myget(datasets, **kwargs):
    if isinstance(datasets, six.string_types):
        return Quandl.get(datasets, **kwargs)
    else:
        d = collections.OrderedDict()
        for dataset in datasets:
            d[dataset] = Quandl.get(datasets, **kwargs)
            columns = list(d[dataset].columns)
            for i, colname in enumerate(columns):
                columns[i] = colname[len(dataset + " - "):]
            d[dataset].columns = columns
        return d  # returns OrderedDict of DataFrame

d = myget(["CHRIS/CME_ES1", "CHRIS/CME_NQ1"])
panel = pd.Panel(d).transpose(2,1,0)

ds = xarray.Dataset(d).to_array()
```

That's not very clean. especially `columns[i] = colname[len(dataset + " - "):]`

But that's just an example

**Comment by junos** [comment]
Hi @femtotrader, 

Thanks for your suggestions. This is an interesting feature suggestion. This is the first time we have seen this type of feature request. For now we will tag it on the next major milestone and decide whether their is a high demand for this type of feature when planning our next major release.
