### ISSUE TITLE
Python client does not use connction pooling / keep-alive

### ISSUE THREAD

**Issue by jkleint** [quandl/quandl-python#78]
The Python client seems to be making an entirely new SSL connection to Quandl for every API call, then throwing it away.  This makes multiple requests very slow and causes unnecessary load on Quandl servers.  Seems like it would be very easy to store a Session in the Connection object.

http://docs.python-requests.org/en/master/user/advanced/#session-objects

**Comment by michaelfich** [comment]
Thank you for bringing this to our attention.  It seems like something which could definitely be beneficial to all parties, and we’d be interested in looking into it in the future.

If you are interested in submitting a pull request to implement this improvement, we’d be happy to review any revisions to the quandl-python package.
