### ISSUE TITLE
3.01 required MS VC++ 1.0

### ISSUE THREAD

**Issue by apassy** [quandl/quandl-python#81]
pip wants to find MSVC++ - I have the complied version of Numpy installed and working (i'm trying to upgrade from 2.89)

**Comment by A-Scott-Rowe** [comment]
Hello Apassy,
Could you answer a few questions to help us troubleshoot?

1. When you say 2.89 are you referring to the Quandl plugin? 
2. Which version of Python are you using and how did you install it? 
3. What version of Numpy is currently installed and how did you install it? It may need to update to work with the latest Quandl plugin.
4. What operating system are you on? 
5. Can you provide an error log?

**Comment by apassy** [comment]
1.  Yes.
2.  WinPython, 3.4.34
3.  Integrated with WinPython, ver 1.9.2
4.  Win 10, 64 bit
5.  attempted via pip, using downloaded whl.

Log:
pip install quandl --upgrade
You are using pip version 7.0.3, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip'
command.
Collecting quandl
  Using cached Quandl-3.0.1-py2.py3-none-any.whl
Collecting requests>=2.7.0 (from quandl)
  Downloading requests-2.12.4-py2.py3-none-any.whl (576kB)
    100% |################################| 577kB 328kB/s
Collecting inflection>=0.3.1 (from quandl)
  Using cached inflection-0.3.1.tar.gz
Collecting python-dateutil (from quandl)
  Downloading python_dateutil-2.6.0-py2.py3-none-any.whl (194kB)
    100% |################################| 196kB 797kB/s
Collecting six (from quandl)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting ndg-httpsclient (from quandl)
  Using cached ndg_httpsclient-0.4.2.tar.gz
Collecting pyasn1 (from quandl)
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Collecting numpy>=1.8 (from quandl)
  Downloading numpy-1.11.2-cp34-none-win_amd64.whl (7.4MB)
    100% |################################| 7.4MB 38kB/s
Collecting more-itertools (from quandl)
  Using cached more-itertools-2.4.1.tar.gz
Collecting pyOpenSSL (from quandl)
  Using cached pyOpenSSL-16.2.0-py2.py3-none-any.whl
Collecting pandas>=0.14 (from quandl)
  Downloading pandas-0.19.1.tar.gz (8.4MB)
    100% |################################| 8.4MB 30kB/s
Collecting cryptography>=1.3.4 (from pyOpenSSL->quandl)
  Downloading cryptography-1.7.1.tar.gz (420kB)
    100% |################################| 421kB 623kB/s
Collecting pytz>=2011k (from pandas>=0.14->quandl)
  Downloading pytz-2016.10-py2.py3-none-any.whl (483kB)
    100% |################################| 487kB 400kB/s
Collecting idna>=2.0 (from cryptography>=1.3.4->pyOpenSSL->quandl)
  Using cached idna-2.1-py2.py3-none-any.whl
Collecting setuptools>=11.3 (from cryptography>=1.3.4->pyOpenSSL->quandl)
  Downloading setuptools-32.0.0-py2.py3-none-any.whl (477kB)
    100% |################################| 479kB 568kB/s
Collecting cffi>=1.4.1 (from cryptography>=1.3.4->pyOpenSSL->quandl)
  Using cached cffi-1.9.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File
"C:\Tools\WinPython-64bit-3.4.3.4\python-3.4.3.amd64\lib\site-packages\setuptools\msvc9_support.py",
line 52, in query_vcvarsall
        return unpatched['query_vcvarsall'](version, *args, **kwargs)
      File
"C:\Tools\WinPython-64bit-3.4.3.4\python-3.4.3.amd64\lib\distutils\msvc9compiler.py",
line 259, in query_vcvarsall
        raise DistutilsPlatformError("Unable to find vcvarsall.bat")
    distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File
"C:\Users\Marc\AppData\Local\Temp\pip-build-9lzlkudz\cffi\setup.py", line
98, in <module>
        if sys.platform == 'win32' and uses_msvc():
      File
"C:\Users\Marc\AppData\Local\Temp\pip-build-9lzlkudz\cffi\setup.py", line
76, in uses_msvc
        return config.try_compile('#ifndef _MSC_VER\n#error "not
MSVC"\n#endif')
      File
"C:\Tools\WinPython-64bit-3.4.3.4\python-3.4.3.amd64\lib\distutils\command\config.py",
line 227, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File
"C:\Tools\WinPython-64bit-3.4.3.4\python-3.4.3.amd64\lib\distutils\command\config.py",
line 133, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File
"C:\Tools\WinPython-64bit-3.4.3.4\python-3.4.3.amd64\lib\distutils\msvc9compiler.py",
line 460, in compile
        self.initialize()
      File
"C:\Tools\WinPython-64bit-3.4.3.4\python-3.4.3.amd64\lib\distutils\msvc9compiler.py",
line 371, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File
"C:\Tools\WinPython-64bit-3.4.3.4\python-3.4.3.amd64\lib\site-packages\setuptools\msvc9_support.py",
line 62, in query_vcvarsall
        raise distutils.errors.DistutilsPlatformError(message)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 10.0 is
required (Unable to find vcvarsall.bat).

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
C:\Users\Marc\AppData\Local\Temp\pip-build-9lzlkudz\cffi


A. Marc Passy
cell:    713/906-2888
fax:     713/489-3646
Gtalk: albertmpassy
http://www.linkedin.com/in/passy

4419 Woodvalley Dr
Houston, TX 77096

**Comment by mbasset** [comment]
Hi @apassy,

It appears as though your distribution (WinPython) does not come with all the necessary dependencies for compiling python modules in windows. To solve this issue you may need to install the visual studio build tools or use a different distribution such as anaconda. This article has more details as to the issue you appear to be having. 
https://blogs.msdn.microsoft.com/pythonengineering/2016/04/11/unable-to-find-vcvarsall-bat/

**Comment by mbasset** [comment]
Hi @apassy. We haven't heard back from you and there hasn't been any activity on this issue recently. We are assuming you were able to resolve your problem with our suggestion. Please feel free to re-open it if you have any further questions or comments.
