### ISSUE TITLE
help me fix error install package quandl

### ISSUE THREAD

**Issue by nhokconan** [quandl/quandl-python#82]
I try install Quandl for python 3 but error appear like this 
http://pastebin.com/NYbD6FJh

**Comment by mbasset** [comment]
@nhokconan It appears as though pip does not have access to write to the directory where python package is installed. Are you using the same user to install the package as you did to install anaconda?

**Comment by mbasset** [comment]
Hi @nhokconan. We haven't heard back from you and there hasn't been any activity on this issue recently. We are assuming you were able to resolve your problem with our suggestion. Please feel free to re-open it if you have any further questions or comments.
