### ISSUE TITLE
Passing `requests` arguments through `get`

### ISSUE THREAD

**Issue by vfilimonov** [quandl/quandl-python#83]
Hello,

it would be good if there was some way to pass arguments to the `requests.get` in the `quandl.get`  method (or `quandl.ApiConfig` class). In particular, the argument `verify=False` which disables verification of the SSL certificate in HTTPS: some companies employ MitM in order to record traffic of employees for the compliance purposes, and in this case `quandl.get` does not work.

Best
Vladimir

**Comment by michaelfich** [comment]
Hey @vfilimonov,

That sounds like a useful feature to add in.  We will consider adding that type of feature in a future release.  In the mean time if you would like to submit a pull request to implement that type of update, we would be happy to review the proposed changes.

**Comment by michaelfich** [comment]
Hi @vfilimonov,

We haven't heard back from you and there hasn't been any activity on this issue recently. We are assuming you were able to resolve your problem with our suggestion. Please feel free to re-open it if you have any further questions or comments.
