### ISSUE TITLE
getting all codes from a database 

### ISSUE THREAD

**Issue by chivalry123** [quandl/quandl-python#92]
I try to get all the codes from FRED using:

quandl.get("FRED/codes")

It does not work... however, did I miss anything? Thank you.

**Comment by mbasset** [comment]
Hi @chivalry123,

The method you are using is not meant for that type of call which will retrieve a zip file containing a list of codes for time-series datasets in that database. To programmatically pull the file you could use something like:

```python
import requests

url = "https://www.quandl.com/api/v3/databases/FRED/codes"
api_key = "<your api key here>"
	
resp = requests.get(url, data={"api_key": api_key}, stream=True)
	
with open("FRED_codes.zip", "wb") as f:
	for chunk in resp.iter_content(chunk_size=1024):
		f.write(chunk)
		f.flush()
```

And then use a library like `zipfile` to extract the csv in the zip.
