### ISSUE TITLE
need support for requests >= 2.18

### ISSUE THREAD

**Issue by clifton** [quandl/quandl-python#98]
We're trying to use `google-cloud-python` to pull data from GCS, but `requests` < 2.18 causes an error.

https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3736#issuecomment-322271190

**Comment by A-Scott-Rowe** [comment]
Hi @clifton 

In the past we experienced issues with `requests` >= 2.18 with older versions of Python. We will investigate using the latest version.

**Comment by clifton** [comment]
@A-Scott-Rowe, does "older versions" include latest 2.7? Thanks for the help!

**Comment by A-Scott-Rowe** [comment]
I tested the plugin with the latest version of `requests` and it appears to work fine. I've updated the plugin so that there is no upper bound on the `requests` version. 

I'll close this issue for now but if you have any other problems please don't hesitate to open another issue.
